version: '3'

tasks:
  default:
    cmds: [npx tsx scripts/tasks.ts]
    silent: true

  bootstrap:
    cmds: [npx tsx scripts/tasks.ts bootstrap]

  up:
    cmds: [npx tsx scripts/tasks.ts up]

  down:
    cmds: [npx tsx scripts/tasks.ts down]

  status:
    aliases: [s]
    cmds: [npx tsx scripts/tasks.ts status]

  run:
    aliases: [r]
    cmds: ["npx tsx scripts/tasks.ts run {{.CLI_ARGS}}"]

  lint:
    aliases: [l]
    cmds: [npx tsx scripts/tasks.ts lint]

  hf:sync:
    cmds: [npx tsx scripts/tasks.ts hf:sync]

  cron:
    cmds: [npx tsx scripts/tasks.ts cron]

  director:
    cmds: ["npx tsx src/step.ts director {{.CLI_ARGS}}"]
    desc: "Run director agent. Args: [run_id|latest|new] [bucket]"

  reporter:
    cmds: ["npx tsx src/step.ts reporter {{.CLI_ARGS}}"]
    desc: "Run reporter agent. Args: [run_id|latest]"

  script:
    cmds: ["npx tsx src/step.ts script {{.CLI_ARGS}}"]
    desc: "Run script agent. Args: [run_id|latest]"

  audio:
    cmds: ["npx tsx src/step.ts audio {{.CLI_ARGS}}"]
    desc: "Run audio agent. Args: [run_id|latest]"

  video:
    cmds: ["npx tsx src/step.ts video {{.CLI_ARGS}}"]
    desc: "Run video agent. Args: [run_id|latest]"