version: '3'

tasks:
  default:
    cmds: 
      - task --list
      - task up
      - task lint
      - task test
    silent: true

  # ============================================================================
  # MAIN WORKFLOW
  # ============================================================================
  run:
    desc: "Run the full workflow (Production Mode)"
    aliases: [r]
    cmds: ["bun src/index.ts {{.CLI_ARGS}}"]

  dryrun:
    desc: "Safe Run: Cached LLM & No Publishing (DRY_RUN=true SKIP_LLM=true)"
    cmds: ["DRY_RUN=true SKIP_LLM=true npx tsx src/index.ts {{.CLI_ARGS}}"]

  run:cached:
    desc: "Run full workflow using cached LLM outputs (WARNING: May Publish)"
    cmds: ["SKIP_LLM=true bun src/index.ts {{.CLI_ARGS}}"]

  # ============================================================================
  # UNIT STEPS
  # ============================================================================
  research:
    desc: "Run research step only"
    cmds: ["bun src/step.ts research {{.CLI_ARGS}}"]

  content:
    desc: "Run content step only"
    cmds: ["bun src/step.ts content {{.CLI_ARGS}}"]

  media:
    desc: "Run media step only"
    cmds: ["bun src/step.ts media {{.CLI_ARGS}}"]

  publish:
    desc: "Run publish step only (REAL PUBLISH)"
    cmds: ["bun src/step.ts publish {{.CLI_ARGS}}"]

  publish:dry:
    desc: "Run publish step in Dry Run mode (No external API calls)"
    cmds: ["DRY_RUN=true bun src/step.ts publish {{.CLI_ARGS}}"]

  # ============================================================================
  # INFRASTRUCTURE
  # ============================================================================
  up:
    desc: "Start background services (Voicevox, Aim, Discord Bot)"
    cmds:
      - docker rm -f voicevox-nemo || true
      - docker run -d --name voicevox-nemo --restart unless-stopped -p 50121:50021 voicevox/voicevox_engine:cpu-ubuntu20.04-latest
      - mkdir -p logs
      - nohup aim up --host 127.0.0.1 --port 43800 > logs/aim.log 2>&1 &
      - nohup bun scripts/discord_news_bot.ts > logs/discord_bot.log 2>&1 &

  down:
    desc: "Stop all background services"
    cmds:
      - docker stop voicevox-nemo || true
      - pkill -f "aim up" || true
      - pkill -f "discord_news_bot" || true

  status:
    desc: "Check status of background services"
    aliases: [s]
    cmds:
      - ps aux | grep -E "(aim|discord_news_bot)" | grep -v grep || true
      - docker ps | grep voicevox-nemo || true

  bootstrap:
    desc: "Install dependencies and setup environment"
    cmds:
      - bun install
      - task up

  serve:
    desc: "Start the HTMX Dashboard to monitor runs"
    cmds: ["bun scripts/dashboard/server.ts"]

  # ============================================================================
  # UTILITIES
  # ============================================================================
  lint:
    desc: "Type-check and Lint"
    aliases: [l]
    cmds:
      - npx tsc --noEmit
      - npx eslint src

  test:
    desc: "Run unit tests (bun test)"
    aliases: [t]
    cmds: ["SKIP_LLM=true DRY_RUN=true bun test"]

  audit:overlays:
    desc: "Audit video overlays"
    cmds: ["bun scripts/audit_overlays.ts"]

  cron:
    desc: "Install cron jobs based on config (Legacy)"
    cmds: ["bun scripts/automation.ts --install-cron"]

  systemd:setup:
    desc: "Install Systemd service and timer"
    cmds: ["bun scripts/setup_systemd.ts"]

  # ============================================================================
  # ACE Intelligence (OpenCE)
  # ============================================================================
  ace:evaluate:
    desc: "Analyze logs and evolve playbook (Closed-Loop)"
    cmds: ["npx tsx --env-file=config/.env scripts/ace_ops.ts evaluate"]

  ace:acquire:
    desc: "Acquire new orthogonal strategic hypotheses"
    cmds: ["npx tsx --env-file=config/.env scripts/ace_ops.ts acquire"]

  monitor:watch:
    desc: "Run the watcher agent manually"
    cmds: ["bun src/agents/watcher.ts {{.CLI_ARGS}}"]
