version: '3'

tasks:
  default:
    cmds: 
      - task --list
      - task up
      - task lint
      - task test
    silent: true

  # ============================================================================
  # MAIN WORKFLOW
  # ============================================================================
  run:
    desc: "Run the full workflow (Production Mode)"
    aliases: [r]
    cmds: ["npx tsx scripts/tasks.ts run {{.CLI_ARGS}}"]

  dryrun:
    desc: "Safe Run: Cached LLM & No Publishing (DRY_RUN=true SKIP_LLM=true)"
    cmds: ["DRY_RUN=true SKIP_LLM=true npx tsx src/index.ts {{.CLI_ARGS}}"]

  run:cached:
    desc: "Run full workflow using cached LLM outputs (WARNING: May Publish)"
    cmds: ["SKIP_LLM=true npx tsx scripts/tasks.ts run {{.CLI_ARGS}}"]

  # ============================================================================
  # UNIT STEPS
  # ============================================================================
  research:
    desc: "Run research step only"
    cmds: ["npx tsx src/step.ts research {{.CLI_ARGS}}"]

  content:
    desc: "Run content step only"
    cmds: ["npx tsx src/step.ts content {{.CLI_ARGS}}"]

  content:fix:
    desc: "Run content step with feedback from The Critic"
    cmds: ["npx tsx src/step.ts content:fix {{.CLI_ARGS}}"]

  media:
    desc: "Run media step only"
    cmds: ["npx tsx src/step.ts media {{.CLI_ARGS}}"]

  publish:
    desc: "Run publish step only (REAL PUBLISH)"
    cmds: ["npx tsx src/step.ts publish {{.CLI_ARGS}}"]

  publish:dry:
    desc: "Run publish step in Dry Run mode (No external API calls)"
    cmds: ["DRY_RUN=true npx tsx src/step.ts publish {{.CLI_ARGS}}"]

  evaluate:
    desc: "Run content evaluation (The Critic)"
    cmds: ["npx tsx src/step.ts evaluate {{.CLI_ARGS}}"]

  # ============================================================================
  # INFRASTRUCTURE
  # ============================================================================
  up:
    desc: "Start background services (Voicevox, Aim, Discord Bot)"
    cmds: [npx tsx scripts/tasks.ts up]

  down:
    desc: "Stop all background services"
    cmds: [npx tsx scripts/tasks.ts down]

  status:
    desc: "Check status of background services"
    aliases: [s]
    cmds: [npx tsx scripts/tasks.ts status]

  bootstrap:
    desc: "Install dependencies and setup environment"
    cmds: [npx tsx scripts/tasks.ts bootstrap]

  serve:
    desc: "Start the HTMX Dashboard to monitor runs"
    cmds: ["npx tsx scripts/dashboard/server.ts"]

  # ============================================================================
  # UTILITIES
  # ============================================================================
  lint:
    desc: "Type-check and Lint"
    aliases: [l]
    cmds:
      - npx tsc --noEmit
      - npx eslint src

  test:
    desc: "Run unit tests (node --test)"
    aliases: [t]
    cmds: [npx tsx scripts/tasks.ts test]

  audit:overlays:
    desc: "Audit video overlays"
    cmds: ["npx tsx scripts/tasks.ts audit:overlays"]

  cron:
    desc: "Install cron jobs based on config (Legacy)"
    cmds: ["npx tsx scripts/tasks.ts cron"]

  systemd:setup:
    desc: "Install Systemd service and timer"
    cmds: ["npx tsx scripts/tasks.ts setup:systemd"]

  monitor:watch:
    desc: "Run the watcher agent manually"
    cmds: ["npx tsx scripts/tasks.ts watcher {{.CLI_ARGS}}"]
