version: '3'

tasks:
  default:
    cmds: [npx tsx scripts/tasks.ts]
    silent: true

  bootstrap:
    cmds: [npx tsx scripts/tasks.ts bootstrap]

  up:
    cmds: [npx tsx scripts/tasks.ts up]

  down:
    cmds: [npx tsx scripts/tasks.ts down]

  status:
    aliases: [s]
    cmds: [npx tsx scripts/tasks.ts status]

  run:
    aliases: [r]
    cmds: ["npx tsx scripts/tasks.ts run {{.CLI_ARGS}}"]

  run:cached:
    cmds: ["SKIP_LLM=true npx tsx scripts/tasks.ts run {{.CLI_ARGS}}"]
    desc: "Run workflow using cached LLM outputs"

  lint:
    aliases: [l]
    cmds: [npx tsx scripts/tasks.ts lint]

  research:
    cmds: ["npx tsx src/step.ts research {{.CLI_ARGS}}"]
  research:cached:
    cmds: ["SKIP_LLM=true npx tsx src/step.ts research {{.CLI_ARGS}}"]

  content:
    cmds: ["npx tsx src/step.ts content {{.CLI_ARGS}}"]
  content:cached:
    cmds: ["SKIP_LLM=true npx tsx src/step.ts content {{.CLI_ARGS}}"]

  media:
    cmds: ["npx tsx src/step.ts media {{.CLI_ARGS}}"]
  media:cached:
    cmds: ["SKIP_LLM=true npx tsx src/step.ts media {{.CLI_ARGS}}"]

  publish:
    cmds: ["npx tsx src/step.ts publish {{.CLI_ARGS}}"]

  audit:overlays:
    cmds: ["npx tsx scripts/tasks.ts audit:overlays"]
  
  dryrun:
    desc: "Run the full workflow in dry-run mode using cached LLM outputs"
    cmds: ["DRY_RUN=true SKIP_LLM=true npx tsx src/index.ts {{.CLI_ARGS}}"]
