version: '3'

tasks:
  default:
    cmds: [npx tsx scripts/tasks.ts]
    silent: true

  bootstrap:
    cmds: [npx tsx scripts/tasks.ts bootstrap]

  up:
    cmds: [npx tsx scripts/tasks.ts up]

  down:
    cmds: [npx tsx scripts/tasks.ts down]

  status:
    aliases: [s]
    cmds: [npx tsx scripts/tasks.ts status]

  run:
    aliases: [r]
    cmds: ["npx tsx scripts/tasks.ts run {{.CLI_ARGS}}"]

  lint:
    aliases: [l]
    cmds: [npx tsx scripts/tasks.ts lint]

  hf:sync:
    cmds: [npx tsx scripts/tasks.ts hf:sync]

  cron:
    cmds: [npx tsx scripts/tasks.ts cron]