version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # ============================================================
  # 🚀 SETUP & SERVICES
  # ============================================================

  bootstrap:
    desc: "Complete first-time setup: deps + models + services + cron"
    cmds:
      - uv sync
      - task hf:sync
      - task up
      - uv run python scripts/automation.py --skip-cron
      - uv run python scripts/automation.py --install-cron
      - task status

  up:
    desc: Start all services (Aim, Voicevox, Discord)
    aliases: [start]
    cmds:
      - nohup bash scripts/start_aim.sh >/dev/null 2>&1 &
      - nohup bash scripts/voicevox_manager.sh start >/dev/null 2>&1 &
      - nohup uv run python scripts/discord_news_bot.py >/dev/null 2>&1 &
      - sleep 2
      - echo "✅ Services started"

  down:
    desc: Stop all services
    aliases: [stop]
    cmds:
      - pkill -f "aim up" || true
      - bash scripts/voicevox_manager.sh stop || true
      - pkill -f "discord_news_bot" || true
      - echo "✅ Services stopped"

  status:
    desc: Check all services status
    aliases: [s]
    cmds:
      - echo "=== Processes ===" && ps aux | grep -E "(aim|voicevox|discord_news_bot)" | grep -v grep || echo "None"
      - echo "=== Docker ===" && docker ps | grep voicevox || echo "Voicevox not running"
      - echo "=== Cron ===" && crontab -l || echo "No cron"
    silent: true

  # ============================================================
  # 🎬 WORKFLOW
  # ============================================================

  run:
    desc: Run main workflow (use -- to pass args)
    aliases: [r]
    cmds:
      - uv run python -m src.main {{.CLI_ARGS}}


  # ============================================================
  # ✅ CODE QUALITY & TEST
  # ============================================================

  check:
    desc: Lint + fast tests
    aliases: [c]
    cmds:
      - uv run ruff check --fix src
      - uv run ruff format src
      - uv run mypy src 

  # ============================================================
  # 🤖 MODELS & AUTOMATION
  # ============================================================

  hf:sync:
    desc: Download and link HF models
    env:
      HF_HOME: "{{.HOME}}/.cache/huggingface"
      HF_HUB_CACHE: "{{.HOME}}/.cache/huggingface/hub"
    cmds:
      - task -d external/hf-cache-hub hf:sync

  cron:
    desc: Install/update cron automation
    cmds:
      - uv run python scripts/automation.py --install-cron
      - crontab -l

  aim:
    desc: Start Aim dashboard (blocking)
    cmds:
      - aim up --host 0.0.0.0 --port 43800