import { NotebookLMAgent } from "./domain/agents/notebooklm.js";
import { PublishAgent } from "./domain/agents/publish.js";
import { AssetStore, getRunIdDateString } from "./io/core.js";
import { AgentLogger } from "./io/utils/logger.js";
import type { AgentState } from "./domain/types.js";

async function main() {
	const args = process.argv.slice(2);
	const notebookTitle = args[0] || `Notebook-${getRunIdDateString()}`;
	const sourceUrl = args[1]; // Optional source URL

	const runId = `nlm-${getRunIdDateString()}`;
	const store = new AssetStore(runId);
	AgentLogger.init();

	const nlmAgent = new NotebookLMAgent(store);
	const publishAgent = new PublishAgent(store);

	try {
		// 1. Create or use existing
		let notebookId: string;
		const firstArg = args[0];
		if (firstArg && (firstArg.startsWith("nb-") || firstArg.length > 20)) {
			// Assume it's an ID if it looks like one
			notebookId = firstArg;
			AgentLogger.info("SYSTEM", "NLM_WORKFLOW", "START", `Using existing notebook: ${notebookId}`);
		} else {
			notebookId = await nlmAgent.createNotebook(notebookTitle);
		}

		// 2. Add source if provided
		if (sourceUrl) {
			await nlmAgent.addSource(notebookId, sourceUrl, undefined, "Primary Workflow Source");
		}

		// 3. Generate and Download
		const result = await nlmAgent.run([notebookId], "whiteboard");
		
		if (result.videos.length === 0) {
			throw new Error("No videos generated");
		}

		const video = result.videos[0];
		if (!video) throw new Error("Video object is undefined");

		// 4. Publish to YouTube
		AgentLogger.info("SYSTEM", "NLM_WORKFLOW", "PUBLISH", `Publishing video to YouTube: ${video.video_path}`);
		
		const state: AgentState = {
			run_id: runId,
			bucket: "notebooklm",
			video_path: video.video_path,
			metadata: {
				title: video.notebook_title,
				description: `Generated by NotebookLM for: ${video.notebook_title}`,
				thumbnail_title: video.notebook_title,
				tags: ["NotebookLM", "AI", "Whiteboard"],
			}
		};

		const publishResult = await publishAgent.run(state);
		
		AgentLogger.info("SYSTEM", "NLM_WORKFLOW", "SUCCESS", "Workflow completed successfully", {
			context: { youtube_id: publishResult.youtube?.video_id }
		});

	} catch (err: any) {
		AgentLogger.error("SYSTEM", "NLM_WORKFLOW", "FAILED", err.message);
		process.exit(1);
	}
}

main();
