import path from "node:path";
import { NotebookLMAgent } from "./domain/agents/notebooklm.js";
import { PublishAgent } from "./domain/agents/publish.js";
import type { AgentState } from "./domain/types.js";
import { AssetStore, getRunIdDateString } from "./io/core.js";
import { AgentLogger } from "./io/utils/logger.js";
import {
	classifyFailureMessage,
	resolveDailyLogPath,
	writeRunEvidence,
} from "./io/utils/stability.js";

async function main() {
	const args = process.argv.slice(2);
	const notebookTitle = args[0] || `Notebook-${getRunIdDateString()}`;
	const sourceUrl = args[1];

	let runId = process.env.RUN_ID || `nlm/${getRunIdDateString()}`;
	if (!runId.includes("/")) {
		runId = `nlm/${runId}`;
	}
	const store = new AssetStore(runId);
	AgentLogger.init();

	const nlmAgent = new NotebookLMAgent(store);
	const publishAgent = new PublishAgent(store);

	try {
		let notebookId: string;
		const firstArg = args[0];
		const isId =
			firstArg &&
			(firstArg.startsWith("nb-") ||
				/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
					firstArg,
				));

		if (isId) {
			notebookId = firstArg;
			AgentLogger.info(
				"SYSTEM",
				"NLM_WORKFLOW",
				"START",
				`Using existing notebook: ${notebookId}`,
			);
		} else {
			notebookId = await nlmAgent.createNotebook(notebookTitle);
		}

		if (sourceUrl) {
			await nlmAgent.addSource(
				notebookId,
				sourceUrl,
				undefined,
				"Primary Workflow Source",
			);
		}

		const result = await nlmAgent.run([notebookId], "whiteboard");

		if (result.videos.length === 0) {
			throw new Error("No videos generated");
		}

		const video = result.videos[0];
		if (!video) throw new Error("Video object is undefined");

		AgentLogger.info(
			"SYSTEM",
			"NLM_WORKFLOW",
			"PUBLISH",
			`Publishing video to YouTube: ${video.video_path}`,
		);

		const state: AgentState = {
			run_id: runId,
			bucket: "notebooklm",
			video_path: video.video_path,
			metadata: {
				title: video.notebook_title,
				description: `Generated by NotebookLM for: ${video.notebook_title}`,
				thumbnail_title: video.notebook_title,
				tags: ["NotebookLM", "AI", "Whiteboard"],
			},
		};

		const publishResult = await publishAgent.run(state);

		AgentLogger.info(
			"SYSTEM",
			"NLM_WORKFLOW",
			"SUCCESS",
			"Workflow completed successfully",
			{
				context: { youtube_id: publishResult.youtube?.video_id },
			},
		);
		writeRunEvidence(store.runDir, {
			run_id: runId,
			bucket: "notebooklm",
			status: "SUCCESS",
			disposition: "success",
			log_path: resolveDailyLogPath(runId),
			evidence_paths: [
				path.join(store.runDir, "state.json"),
				path.join(store.runDir, "publish", "receipt.json"),
			],
			artifact_paths: [video.video_path],
			note: "NotebookLM standalone workflow completed successfully.",
		});
	} catch (err: unknown) {
		const error = err as Error;
		const failure = classifyFailureMessage(error.message);
		AgentLogger.error("SYSTEM", "NLM_WORKFLOW", "FAILED", error.message);

		writeRunEvidence(store.runDir, {
			run_id: runId,
			bucket: "notebooklm",
			status: failure.disposition === "blocked" ? "PUBLISH_BLOCKED" : "PENDING",
			disposition: failure.disposition,
			log_path: resolveDailyLogPath(runId),
			evidence_paths: [path.join(store.runDir, "state.json")],
			artifact_paths: [],
			failure,
			note: "NotebookLM workflow failed. Fallback reuse is prohibited.",
		});
		process.exit(1);
	}
}

main();
