import { NotebookLMAgent } from "./domain/agents/notebooklm.js";
import { PublishAgent } from "./domain/agents/publish.js";
import type { AgentState } from "./domain/types.js";
import { AssetStore, getRunIdDateString } from "./io/core.js";
import { AgentLogger } from "./io/utils/logger.js";

async function main() {
	const args = process.argv.slice(2);
	const notebookTitle = args[0] || `Notebook-${getRunIdDateString()}`;
	const sourceUrl = args[1];

	const runId = `nlm-${getRunIdDateString()}`;
	const store = new AssetStore(runId);
	AgentLogger.init();

	const nlmAgent = new NotebookLMAgent(store);
	const publishAgent = new PublishAgent(store);

	try {
		let notebookId: string;
		const firstArg = args[0];
		// Check if it's a UUID or nb- prefixed ID
		const isId =
			firstArg &&
			(firstArg.startsWith("nb-") ||
				/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
					firstArg,
				));

		if (isId) {
			notebookId = firstArg;
			AgentLogger.info(
				"SYSTEM",
				"NLM_WORKFLOW",
				"START",
				`Using existing notebook: ${notebookId}`,
			);
		} else {
			notebookId = await nlmAgent.createNotebook(notebookTitle);
		}

		if (sourceUrl) {
			await nlmAgent.addSource(
				notebookId,
				sourceUrl,
				undefined,
				"Primary Workflow Source",
			);
		}

		const result = await nlmAgent.run([notebookId], "whiteboard");

		if (result.videos.length === 0) {
			throw new Error("No videos generated");
		}

		const video = result.videos[0];
		if (!video) throw new Error("Video object is undefined");

		AgentLogger.info(
			"SYSTEM",
			"NLM_WORKFLOW",
			"PUBLISH",
			`Publishing video to YouTube: ${video.video_path}`,
		);

		const state: AgentState = {
			run_id: runId,
			bucket: "notebooklm",
			video_path: video.video_path,
			metadata: {
				title: video.notebook_title,
				description: `Generated by NotebookLM for: ${video.notebook_title}`,
				thumbnail_title: video.notebook_title,
				tags: ["NotebookLM", "AI", "Whiteboard"],
			},
		};

		const publishResult = await publishAgent.run(state);

		AgentLogger.info(
			"SYSTEM",
			"NLM_WORKFLOW",
			"SUCCESS",
			"Workflow completed successfully",
			{
				context: { youtube_id: publishResult.youtube?.video_id },
			},
		);
	} catch (err: unknown) {
		AgentLogger.error(
			"SYSTEM",
			"NLM_WORKFLOW",
			"FAILED",
			(err as { message: string }).message,
		);
		process.exit(1);
	}
}

main();
