import path from "node:path";
import fs from "fs-extra";
import { TrendScout } from "./domain/agents/research.js";
import { NotebookLMAgent } from "./domain/agents/notebooklm.js";
import { PublishAgent } from "./domain/agents/publish.js";
import { AssetStore, getRunIdDateString, ROOT } from "./io/core.js";
import { AgentLogger } from "./io/utils/logger.js";
import type { AgentState } from "./domain/types.js";

async function main() {
	const runId = `pulse-nlm-${getRunIdDateString()}`;
	const store = new AssetStore(runId);
	AgentLogger.init();

	AgentLogger.info("SYSTEM", "PULSE_WORKFLOW", "START", `Starting Daily Pulse to NotebookLM Workflow (RunID: ${runId})`);

	const scout = new TrendScout(store);
	const nlmAgent = new NotebookLMAgent(store);
	const publishAgent = new PublishAgent(store);

	try {
		// 1. Research: Extract topic and news from pulse.md
		AgentLogger.info("SYSTEM", "PULSE_WORKFLOW", "RESEARCH", "Extracting daily pulse topics...");
		const research = await scout.run("daily_pulse");
		
		if (!research.director_data.title_hook) {
			throw new Error("Failed to extract a title hook from research");
		}

		const title = research.director_data.title_hook;
		const newsItems = research.news;

		AgentLogger.info("SYSTEM", "PULSE_WORKFLOW", "TOPIC", `Selected Topic: ${title}`);

		// 2. NotebookLM: Create and Setup
		const notebookId = await nlmAgent.createNotebook(title);
		
		// Add pulse.md as the primary text source
		const pulsePath = path.join(ROOT, "pulse.md");
		if (fs.existsSync(pulsePath)) {
			const pulseContent = fs.readFileSync(pulsePath, "utf8");
			await nlmAgent.addSource(notebookId, pulseContent, "text");
		}

		// Add discovered news URLs as sources
		for (const item of newsItems) {
			if (item.url && item.url.startsWith("http")) {
				try {
					await nlmAgent.addSource(notebookId, item.url, "url");
				} catch (e) {
					AgentLogger.warn("SYSTEM", "PULSE_WORKFLOW", "SOURCE_WARN", `Failed to add source URL: ${item.url}`);
				}
			}
		}

		// 3. Generate and Download Video
		AgentLogger.info("SYSTEM", "PULSE_WORKFLOW", "GENERATE", "Generating NotebookLM video...");
		const nlmResult = await nlmAgent.run([notebookId], "whiteboard");
		
		if (nlmResult.videos.length === 0) {
			throw new Error("No video was generated by NotebookLM");
		}

		const video = nlmResult.videos[0];
		if (!video) throw new Error("Video object is undefined");

		// 4. Publish to YouTube
		AgentLogger.info("SYSTEM", "PULSE_WORKFLOW", "PUBLISH", `Publishing to YouTube: ${video.video_path}`);
		
		const state: AgentState = {
			run_id: runId,
			bucket: "daily_pulse_nlm",
			video_path: video.video_path,
			metadata: {
				title: title,
				description: `【Daily Pulse】${title}\n\n今日の最重要マーケットトピックをNotebookLMで深掘り解説。ソース：pulse.md および最新ニュース。\n\n#経済 #金融 #NotebookLM #AI #マーケット`,
				thumbnail_title: title,
				tags: ["経済", "金融", "NotebookLM", "AI", "マーケット", "Daily Pulse"],
			}
		};

		const publishResult = await publishAgent.run(state);

		AgentLogger.info("SYSTEM", "PULSE_WORKFLOW", "SUCCESS", "Workflow completed successfully!", {
			context: { youtube_id: publishResult.youtube?.video_id }
		});

	} catch (err: any) {
		AgentLogger.error("SYSTEM", "PULSE_WORKFLOW", "FAILED", err.message);
		process.exit(1);
	}
}

main();
