import path from "node:path";
import fs from "fs-extra";
import { NotebookLMAgent } from "./domain/agents/notebooklm.js";
import { PublishAgent } from "./domain/agents/publish.js";
import { TrendScout } from "./domain/agents/research.js";
import type { AgentState } from "./domain/types.js";
import { AssetStore, ROOT, getRunIdDateString } from "./io/core.js";
import { AgentLogger } from "./io/utils/logger.js";
import {
	classifyFailureMessage,
	resolveDailyLogPath,
	writeRunEvidence,
} from "./io/utils/stability.js";

async function main() {
	let runId = process.env.RUN_ID || `pulse_nlm/${getRunIdDateString()}`;
	if (!runId.includes("/")) {
		runId = `pulse_nlm/${runId}`;
	}
	const store = new AssetStore(runId);
	AgentLogger.init();

	AgentLogger.info(
		"SYSTEM",
		"PULSE_WORKFLOW",
		"START",
		`Starting Daily Pulse to NotebookLM Workflow (RunID: ${runId})`,
	);

	const scout = new TrendScout(store);
	const nlmAgent = new NotebookLMAgent(store);
	const publishAgent = new PublishAgent(store);

	try {
		AgentLogger.info(
			"SYSTEM",
			"PULSE_WORKFLOW",
			"RESEARCH",
			"Extracting daily pulse topics...",
		);
		const research = await scout.run("daily_pulse");

		if (!research.director_data.title_hook) {
			throw new Error("Failed to extract a title hook from research");
		}

		const title = research.director_data.title_hook;
		const searchQuery = research.director_data.search_query;
		const newsItems = research.news;

		AgentLogger.info(
			"SYSTEM",
			"PULSE_WORKFLOW",
			"TOPIC",
			`Selected Topic: ${title}`,
		);

		const notebookId = await nlmAgent.createNotebook(title);

		const pulsePath = path.join(ROOT, "pulse.md");
		if (fs.existsSync(pulsePath)) {
			const pulseContent = fs.readFileSync(pulsePath, "utf8");
			await nlmAgent.addSource(
				notebookId,
				pulseContent,
				"text",
				"Daily Pulse Sovereignty Data",
			);
		}

		if (searchQuery) {
			AgentLogger.info(
				"SYSTEM",
				"PULSE_WORKFLOW",
				"DEEP_RESEARCH",
				`Starting deep research in NotebookLM for: ${searchQuery}`,
			);
			await nlmAgent.deepResearch(notebookId, searchQuery);
		}

		for (const item of newsItems) {
			if (item.url?.startsWith("http")) {
				try {
					await nlmAgent.addSource(notebookId, item.url, "url");
				} catch (e) {
					AgentLogger.warn(
						"SYSTEM",
						"PULSE_WORKFLOW",
						"SOURCE_WARN",
						`Failed to add source URL: ${item.url}`,
					);
				}
			}
		}

		AgentLogger.info(
			"SYSTEM",
			"PULSE_WORKFLOW",
			"GENERATE",
			"Generating NotebookLM video...",
		);
		const nlmResult = await nlmAgent.run([notebookId], "whiteboard");

		if (nlmResult.videos.length === 0) {
			throw new Error("No video was generated by NotebookLM");
		}

		const video = nlmResult.videos[0];
		if (!video) throw new Error("Video object is undefined");

		AgentLogger.info(
			"SYSTEM",
			"PULSE_WORKFLOW",
			"PUBLISH",
			`Publishing to YouTube: ${video.video_path}`,
		);

		const state: AgentState = {
			run_id: runId,
			bucket: "daily_pulse_nlm",
			video_path: video.video_path,
			metadata: {
				title: title,
				description: `【Daily Pulse】${title}\n\n今日の最重要マーケットトピックをNotebookLMで深掘り解説。ソース：pulse.md および最新ニュース。\n\n#経済 #金融 #NotebookLM #AI #マーケット`,
				thumbnail_title: title,
				tags: ["経済", "金融", "NotebookLM", "AI", "マーケット", "Daily Pulse"],
			},
		};

		const publishResult = await publishAgent.run(state);

		AgentLogger.info(
			"SYSTEM",
			"PULSE_WORKFLOW",
			"SUCCESS",
			"Workflow completed successfully!",
			{
				context: { youtube_id: publishResult.youtube?.video_id },
			},
		);
		writeRunEvidence(store.runDir, {
			run_id: runId,
			bucket: "daily_pulse_nlm",
			status: "SUCCESS",
			disposition: "success",
			log_path: resolveDailyLogPath(runId),
			evidence_paths: [
				path.join(store.runDir, "state.json"),
				path.join(store.runDir, "publish", "receipt.json"),
			],
			artifact_paths: [video.video_path],
			note: "NotebookLM workflow completed successfully.",
		});
	} catch (err: unknown) {
		const error = err as Error;
		const failure = classifyFailureMessage(error.message);
		AgentLogger.error("SYSTEM", "PULSE_WORKFLOW", "FAILED", error.message);

		writeRunEvidence(store.runDir, {
			run_id: runId,
			bucket: "daily_pulse_nlm",
			status: failure.disposition === "blocked" ? "PUBLISH_BLOCKED" : "PENDING",
			disposition: failure.disposition,
			log_path: resolveDailyLogPath(runId),
			evidence_paths: [path.join(store.runDir, "state.json")],
			artifact_paths: [],
			failure,
			note: "NotebookLM workflow failed. Fallback reuse and fallback publishing are prohibited.",
		});
		process.exit(1);
	}
}

main();
